# Generated by Django 5.1.3 on 2024-12-09 19:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house_number', models.PositiveIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название поставщика')),
                ('supplier_type', models.CharField(choices=[('З', 'Завод'), ('РС', 'Розничная сеть'), ('ИП', 'Индивидуальный предприниматель')], max_length=35, verbose_name='тип поставщика')),
                ('debt_to_supplier', models.FloatField(default=0, verbose_name='долг перед поставщиком')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2024, 12, 9, 19, 14, 1, 992609, tzinfo=datetime.timezone.utc), verbose_name='время создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suppliers.contact', verbose_name='контакт')),
                ('product', models.ManyToManyField(blank=True, null=True, to='suppliers.product', verbose_name='продукты')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='поставщик')),
            ],
        ),
    ]
